spring:
  application:
    name: ftgo-api-gateway
  cloud:
    gateway:
      discovery:
        healthCheckPath: actuator/health
        healthCheckInterval: 15s
        locator:
          enabled: true
      routes:
        - id: ftgo-consumer-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/consumer-resource/**
          filters:
            - RewritePath=/api/consumer-resource/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
        - id: courier-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/courier-resource/**
          filters:
            - RewritePath=/api/courier-resource/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
        - id: openapi
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/openapi
          uri: http://localhost:${server.port}
    loadbalancer:
      ribbon:
        enabled: false

springdoc:
  swagger-ui:
    urls:
      - name: users
        url: /api/user-resource/openapi
      - name: trips
        url: /api/trip-resource/openapi