version: '3'
services:
  ftgo-database:
    image: mysql:latest
    environment:
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'mysqlpw'
      MYSQL_ROOT_PASSWORD: 'mysqlrootpw'
    ports:
      - "3306:3306"
    expose:
      - '3306'
  ftgo-consumer-service:
    build:
      context: ftgo-consumer-service/ftgo-consumer-starter
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
  ftgo-courier-service:
    build:
      context: ftgo-courier-service/ftgo-courier-starter
      dockerfile: Dockerfile
    ports:
      - "8092:8092"