spring:
  cloud:
    gateway:
      routes:
      - id: ftgo-consumer-service
        uri: http://localhost:8091
        predicates:
          - Path=/api/v1/consumers/**
        filters:
          - RewritePath=/(?<segment>/?.*), /$\{segment}
      - id: ftgo-courier-service
        uri: http://localhost:8092
        predicates:
          - Path=/api/v1/couriers/**
        filters:
          - RewritePath=/(?<segment>/?.*), /$\{segment}
      - id: ftgo-monolith
        uri: http://localhost:8090
        predicates:
          - Path=/monolith/**
        filters:
          - RewritePath=/monolith(?<segment>/?.*), $\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
