name: pipeline

on: [push]

jobs:
  build-project-and-publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Build Spring Project
      run: ./gradlew build

    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/michael-neuhold/ftgo-services:latest
        docker push ghcr.io/michael-neuhold/ftgo-services:latest
